# Generated by Django 5.0.4 on 2024-07-05 23:54

from django.db import migrations, models
from django.template.defaultfilters import slugify


def set_slug_for_existing_debates(apps, schema_editor):
    Debate = apps.get_model('debate', 'Debate')
    for debate in Debate.objects.all():
        debate.slug = slugify(debate.title)
        debate.save()


class Migration(migrations.Migration):
    dependencies = [
        ('debate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='slug',
            field=models.SlugField(default=None, null=True, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.RunPython(set_slug_for_existing_debates, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='debate',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
