# Generated by Django 5.0.4 on 2024-12-17 20:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0005_debate_search_vector_debate_search_vector_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stance',
            index=models.Index(fields=['user', '-created_at'], name='debate_stan_user_id_46459d_idx'),
        ),
        migrations.AddIndex(
            model_name='stance',
            index=models.Index(fields=['user', 'debate'], name='debate_stan_user_id_a1af96_idx'),
        ),
    ]
