# Generated by Django 5.0.4 on 2024-10-11 00:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_readcheckpoint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['discussion', '-created_at'], name='discussion__discuss_31bb37_idx'),
        ),
        migrations.AddIndex(
            model_name='readcheckpoint',
            index=models.Index(fields=['discussion', 'user'], name='discussion__discuss_2b3c1d_idx'),
        ),
    ]
