# Generated by Django 5.0.4 on 2024-05-14 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0003_discussionrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussionrequest',
            old_name='wants_opposite',
            new_name='stance_wanted',
        ),
    ]
