# Generated by Django 5.0.4 on 2024-12-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0003_message_discussion__discuss_31bb37_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='is_archived_for_p1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discussion',
            name='is_archived_for_p2',
            field=models.BooleanField(default=False),
        ),
    ]
