# Generated by Django 5.0.4 on 2024-12-30 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('debate', '0006_stance_debate_stan_user_id_46459d_idx_and_more'),
        ('discussion', '0004_discussion_is_archived_for_p1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PairingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_stance', models.BooleanField()),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('active', 'Active'), ('passive', 'Passive'), ('match_found', 'Match Found'), ('paired', 'Paired')], default='idle', max_length=25)),
                ('last_keepalive_ping', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debate.debate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PairingMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_discussion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='related_discussion', to='discussion.discussion')),
                ('pairing_request_1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pairing_request_1', to='pairing.pairingrequest')),
                ('pairing_request_2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pairing_request_2', to='pairing.pairingrequest')),
            ],
        ),
    ]
