# Generated by Django 5.0.4 on 2025-01-09 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0004_discussion_is_archived_for_p1_and_more'),
        ('pairing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairingmatch',
            name='related_discussion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_discussion', to='discussion.discussion'),
        ),
    ]
