# Generated by Django 5.0.4 on 2024-12-13 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debateme', '0003_alter_invite_code'),
        ('discussion', '0004_discussion_is_archived_for_p1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inviteuse',
            name='resulting_discussion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='discussion.discussion'),
        ),
    ]
